import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} w-dvw h-dvh`}>
        <header className="w-full  bg-slate-500 flex gap-8">
          <Link className="hover:bg-slate-600 p-4" href="/">
            Home
          </Link>
          <Link className="hover:bg-slate-600 p-4" href="/shop">
            Shop
          </Link>
          <Link className="hover:bg-slate-600 p-4" href="/product-list">
            Products
          </Link>
          <Link className="hover:bg-slate-600 p-4" href="/add-product">
            Add Product
          </Link>
          <Link className="hover:bg-slate-600 p-4" href="/admin-product-list">
            Admin Product
          </Link>
        </header>
        {children}
      </body>
    </html>
  );
}
