import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LogoutButton from "./components/Header/LogoutButton";
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body className={`${inter.className} w-dvw h-dvh`}>
        <Header />
        <main className="w-full h-[calc(100%-56px)] mx-auto px-4 py-8 overflow-auto">
          {children}
        </main>
      </body>
    </html>
  );
}
